version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'NPM: '
    target-branch: 'dependabot-target'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ACTIONS: '
      include: 'scope'
    target-branch: 'dependabot-target'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'DOCKER: '
      include: 'scope'
    target-branch: 'dependabot-target'
