version: '3.8'

services:
  postgres:
    image: postgres:16rc1-alpine
    container_name: postgres
    ports:
      - '5433:5432'
    env_file:
      - ./.env
    volumes:
      - postgresdevdb:/var/lib/postgresql/data

volumes:
  postgresdevdb:
