# For development purposes only, not production!!!
version: '3.8'

services:
  test-db:
    image: postgres:16.0-bookworm
    container_name: postgres-test
    ports:
      - '127.0.0.1:5434:5432'
    env_file: .env.test
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgrestestdb:/var/lib/postgresql/data

volumes:
  postgrestestdb:
