version: '3.8'

services:
  dev-db:
    image: postgres:16.0-bookworm
    container_name: postgres-dev
    ports:
      - '127.0.0.1:5433:5432'
    env_file: .env
    volumes:
      - postgresdevdb:/var/lib/postgresql/data

volumes:
  postgresdevdb:
