version: '3.8'

services:
  test-db:
    image: postgres:16.0-bookworm
    container_name: postgres-test
    ports:
      - '127.0.0.1:5433:5432'
    env_file: .env
    volumes:
      - postgrestestdb:/var/lib/postgresql/data

volumes:
  postgrestestdb:
