# For development testing purposes
version: '3.8'

services:
  traininghub-psql:
    image: postgres:16.0-bookworm
    container_name: postgres
    ports:
      - '127.0.0.1:5433:5432'
    env_file:
      - ./.env
    volumes:
      - postgresdevdb:/var/lib/postgresql/data
  app:
    depends_on:
      - traininghub-psql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    env_file: .env.dev # db url traininghub-psql:5432

volumes:
  postgresdevdb:
