name: Deploy to production flow

on:
  push:
    branches: [main]

jobs:
  production-deploy:
    uses: ./.github/workflows/heroku-deploy.yml
    with:
      ENVIRONMENT_NAME: production
    secrets: inherit
