name: Deployment pipeline to production

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install npm
        run: npm ci
      - name: lint
        run: npm run lint
      - name: prettier
        run: npm run test:format
      - name: test
        run: npm run test:ci
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    needs: [test]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_build_args: |
            HUSKY
            NODE_ENV
            DATABASE_URL
        env:
          HUSKY: 0
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
