name: Daily course reminder
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Daily course reminder
        run: |
          curl --request POST \
          --url ${{ secrets.REMINDER_API_URL }} \
          --header "Authorization: Bearer ${{ secrets.API_AUTH_TOKEN }}"
