name: Daily course reminder
on:
  schedule:
    - cron: '0 9 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Daily course reminder
        env:
          REMINDER_API_URL: ${{ secrets.REMINDER_API_URL }}
        run: |
          curl --request POST \
          --url $REMINDER_API_URL \
          --header "Authorization: Bearer ${{ secrets.API_AUTH_TOKEN }}"
