name: Deployment pipeline to staging

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
    types: [opened, synchronize, ready_for_review]

jobs:
  smoke-test:
    uses: ./.github/workflows/smoke-test.yml
    if: ${{ !github.event.pull_request.draft }}
  unit-test:
    uses: ./.github/workflows/unit-test.yml
    needs: [smoke-test]
    secrets: inherit
  e2e-test:
    uses: ./.github/workflows/e2e-test.yml
    needs: [smoke-test]
    secrets: inherit
  staging-deploy:
    uses: ./.github/workflows/heroku-deploy.yml
    needs: ['unit-test', 'e2e-test']
    with:
      ENVIRONMENT_NAME: staging
