name: Deployment pipeline to staging

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
    types: [opened, synchronize, ready_for_review]

jobs:
  smoke-test:
    uses: ./.github/workflows/smoke-test.yml
    if: ${{ !github.event.pull_request.draft }}
  unit-test:
    uses: ./.github/workflows/unit-test.yml
    needs: [smoke-test]
  e2e-test:
    uses: ./.github/workflows/e2e-test.yml
    needs: [smoke-test]

  deploy:
    runs-on: ubuntu-22.04
    environment: staging
    if: ${{ github.event_name == 'push' }}
    needs: [smoke-test, e2e-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_build_args: |
            NEXTAUTH_URL
            NEXTAUTH_SECRET
            SENTRY_ENVIRONMENT
            NEXT_PUBLIC_SENTRY_ENVIRONMENT
            SENTRY_AUTH_TOKEN
            SENTRY_ORG
            SENTRY_PROJECT
        env:
          # NEXTAUTH
          HD_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          HD_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

          # GOOGLE
          HD_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          HD_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

          # SENTRY
          HD_SENTRY_ENVIRONMENT: 'staging'
          HD_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          HD_SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          HD_SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

          # BUILD TIME ARGS

          # NEXTAUTH
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

          # SENTRY
          SENTRY_ENVIRONMENT: 'staging'
          NEXT_PUBLIC_SENTRY_ENVIRONMENT: 'staging'
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
