name: Deployment pipeline to staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches: [staging]
    types: [opened, synchronize]

env:
  HUSKY: 0

jobs:
  smoke-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint:test
      - name: prettier
        run: npm run format:test
      - name: build
        run: npm run build
  test:
    runs-on: ubuntu-22.04
    environment: testing
    needs: [smoke-test]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
        options: >-
          --health-cmd pg_isready  --health-interval 10s  --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: migrate database
        run: npx prisma migrate deploy
      - name: test
        run: npm run test:ci
  deploy:
    runs-on: ubuntu-22.04
    environment: staging
    needs: [test]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_build_args: |
            NEXTAUTH_URL
            NEXTAUTH_SECRET
            SENTRY_ENVIRONMENT
            NEXT_PUBLIC_SENTRY_ENVIRONMENT
            SENTRY_AUTH_TOKEN
            SENTRY_ORG
            SENTRY_PROJECT
        env:
          # NEXTAUTH
          HD_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          HD_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

          # GOOGLE
          HD_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          HD_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

          # SENTRY
          HD_SENTRY_ENVIRONMENT: 'staging'
          HD_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          HD_SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          HD_SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

          # BUILD TIME ARGS

          # NEXTAUTH
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

          # SENTRY
          SENTRY_ENVIRONMENT: 'staging'
          NEXT_PUBLIC_SENTRY_ENVIRONMENT: 'staging'
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
