name: Unit test flow

on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'admin'
          POSTGRES_PASSWORD: 'password'
        options: >-
          --health-cmd pg_isready  --health-interval 10s  --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    env:
      DATABASE_URL: 'postgresql://admin:password@localhost:5433/traininghub-db?schema=public'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: migrate database
        run: npx prisma migrate deploy
      - name: test
        run: npm run test:ci
